[project]
name = "mcpweather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopy>=2.4.1",
    "mcp[cli]>=1.11.0",
    "requests>=2.32.4",
]
